[package]
name = "guh-usb-msc"
version = "0.0.0"
edition = "2021"
categories = ["embedded", "hardware-support", "no-std"]
description = "RISCV/Rust HAL for guh's custom usb msc peripheral."

[lib]
test = true
bench = false

[dependencies]
guh-dma = { path = "../guh-dma" }
critical-section = "1"
log = "0.4.*"
fatfs = { git = "https://github.com/vk2seb/rust-fatfs.git", branch = "seb/dma-geo", default-features = false, optional = true }

[features]
default = []
# without this you only get the raw hal layer - this gives you fs ops from rust-fatfs
fatfs = ["dep:fatfs"]
